import { Download, Share2, CheckCircle, AlertTriangle } from "lucide-react";
import { useNavigate } from "react-router";
import { Header } from "./Header";
import { toast } from "sonner";
import { useApp } from "../context/AppContext";
import { Scores } from "../context/AppContext";

function fmt(n: number) {
  return '$' + Number(n).toLocaleString();
}

function scoreBadge(score: number) {
  const pct = Math.round(score * 100);
  const color = pct >= 75 ? 'bg-green-100 text-green-800' : pct >= 40 ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-800';
  return { pct, color };
}

const TODAY = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

export function MemoScreen() {
  const navigate = useNavigate();
  const { analysisResult, scores, timeline } = useApp();

  if (!analysisResult || !scores) {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col">
        <Header />
        <main className="flex-1 flex items-center justify-center px-6">
          <div className="text-center">
            <AlertTriangle className="w-12 h-12 text-amber-500 mx-auto mb-4" />
            <p className="text-gray-700 mb-4">No analysis results yet.</p>
            <button onClick={() => navigate('/upload')} className="bg-black text-white px-5 py-2 rounded-lg font-semibold">
              Upload Evidence
            </button>
          </div>
        </main>
      </div>
    );
  }

  const strength = Math.round((analysisResult.overall_strength ?? 0) * 100);
  const wbMin = Math.round(analysisResult.total_exposure * 0.15);
  const wbMax = Math.round(analysisResult.total_exposure * 0.25);
  const minPenalty = 13946 * analysisResult.total_false_claims;

  const scoreEntries: { label: string; key: keyof Scores }[] = [
    { label: 'Falsity', key: 'falsity' },
    { label: 'Scienter (Knowledge)', key: 'scienter' },
    { label: 'Materiality', key: 'materiality' },
    { label: 'Causation', key: 'causation' },
  ];

  const handleDownload = () => {
    const lines = [
      'QUITAM COPILOT — CASE ANALYSIS MEMORANDUM',
      '='.repeat(50),
      '',
      `Date: ${TODAY}`,
      'Classification: Confidential Attorney Work Product',
      '',
      'DEFENDANT INFORMATION',
      '-'.repeat(30),
      `Entity: ${analysisResult.defendant}`,
      timeline ? `Fraud Period: ${timeline.fraud_start} - ${timeline.fraud_end}` : '',
      `False Claims: ${Number(analysisResult.total_false_claims).toLocaleString()}`,
      '',
      'FCA ELEMENT SCORES',
      '-'.repeat(30),
      ...scoreEntries.map(e => `${e.label.padEnd(22)} ${Math.round(scores[e.key] * 100)}%`),
      '',
      'DAMAGES ASSESSMENT',
      '-'.repeat(30),
      `Base Damages:        ${fmt(analysisResult.base_damages)}`,
      `Treble Damages (3x): ${fmt(analysisResult.treble_damages)}`,
      `Civil Penalties:     ${fmt(minPenalty)}`,
      `Total Exposure:      ${fmt(analysisResult.total_exposure)}`,
      `Relator Share:       ${fmt(wbMin)} - ${fmt(wbMax)}`,
      '',
      'CASE SUMMARY',
      '-'.repeat(30),
      analysisResult.case_summary,
      '',
      `Overall Strength: ${strength}%`,
      '='.repeat(50),
      'Generated by QuiTam Copilot — Not a substitute for legal advice',
    ].join('\n');

    const blob = new Blob([lines], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `case_memo_${analysisResult.defendant.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Case memo downloaded");
  };

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href).catch(() => {});
    toast.success("Link copied to clipboard");
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <Header />

      <main className="flex-1 max-w-5xl mx-auto w-full px-6 py-12">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Case Memo Ready</h1>
          <p className="text-gray-600">Court-ready analysis</p>
        </div>

        <div className="bg-white border-2 border-gray-300 rounded-lg mb-6 overflow-hidden">
          <div className="bg-gray-50 border-b border-gray-300 px-8 py-6">
            <h2 className="text-xl font-bold text-gray-900 mb-1">
              United States ex rel. [Relator] v. {analysisResult.defendant}
            </h2>
            <p className="text-sm text-gray-600">Case Analysis Memorandum</p>
            <p className="text-sm text-gray-600">{TODAY}</p>
            <p className="text-xs text-gray-500 mt-2 uppercase tracking-wide">
              Confidential Attorney Work Product
            </p>
          </div>

          <div className="px-8 py-6 space-y-6">
            <section>
              <h3 className="font-bold text-gray-900 mb-3 text-sm uppercase tracking-wide">
                Defendant Information
              </h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <p className="text-gray-600">Entity</p>
                  <p className="font-semibold text-gray-900">{analysisResult.defendant}</p>
                </div>
                <div>
                  <p className="text-gray-600">Claim Count</p>
                  <p className="font-semibold text-gray-900">
                    {Number(analysisResult.total_false_claims).toLocaleString()} false claims
                  </p>
                </div>
                {timeline && (
                  <>
                    <div>
                      <p className="text-gray-600">Fraud Period</p>
                      <p className="font-semibold text-gray-900">{timeline.fraud_start} – {timeline.fraud_end}</p>
                    </div>
                    <div>
                      <p className="text-gray-600">Duration</p>
                      <p className="font-semibold text-gray-900">{timeline.total_duration_months} months</p>
                    </div>
                  </>
                )}
              </div>
            </section>

            <section>
              <h3 className="font-bold text-gray-900 mb-3 text-sm uppercase tracking-wide">
                FCA Elements
              </h3>
              <div className="space-y-2">
                {scoreEntries.map(({ label, key }) => {
                  const { pct, color } = scoreBadge(scores[key]);
                  return (
                    <div key={key} className="flex items-center justify-between py-2 border-b border-gray-200">
                      <span className="text-gray-900">{label}</span>
                      <span className={`px-3 py-1 rounded-full text-sm font-semibold ${color}`}>{pct}%</span>
                    </div>
                  );
                })}
              </div>
            </section>

            <section>
              <h3 className="font-bold text-gray-900 mb-3 text-sm uppercase tracking-wide">
                Damages Assessment
              </h3>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-600">Base False Claims</span>
                  <span className="font-semibold text-gray-900">{fmt(analysisResult.base_damages)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Treble Damages (3×)</span>
                  <span className="font-semibold text-gray-900">{fmt(analysisResult.treble_damages)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Civil Penalties (min $13,946 × {Number(analysisResult.total_false_claims).toLocaleString()})</span>
                  <span className="font-semibold text-gray-900">{fmt(minPenalty)}</span>
                </div>
                <div className="flex justify-between pt-3 border-t-2 border-gray-300">
                  <span className="font-bold text-gray-900">Total Maximum Exposure</span>
                  <span className="font-bold text-green-700 text-lg">{fmt(analysisResult.total_exposure)}</span>
                </div>
                <div className="flex justify-between pt-2">
                  <span className="text-gray-600">Relator Share (15–25%)</span>
                  <span className="font-semibold text-teal-700">{fmt(wbMin)} – {fmt(wbMax)}</span>
                </div>
              </div>
            </section>

            <section>
              <h3 className="font-bold text-gray-900 mb-3 text-sm uppercase tracking-wide">
                Case Summary
              </h3>
              <p className="text-gray-700 text-sm leading-relaxed">{analysisResult.case_summary}</p>
            </section>

            <section className={`${strength >= 75 ? 'bg-green-50 border-green-600' : strength >= 50 ? 'bg-amber-50 border-amber-500' : 'bg-red-50 border-red-500'} border-l-4 p-4 rounded`}>
              <div className="flex items-start gap-3">
                <CheckCircle className={`w-5 h-5 ${strength >= 75 ? 'text-green-600' : strength >= 50 ? 'text-amber-500' : 'text-red-500'} flex-shrink-0 mt-0.5`} />
                <div>
                  <p className="font-bold text-gray-900 mb-1">
                    {strength >= 75 ? 'Strong' : strength >= 50 ? 'Moderate' : 'Developing'} Case Quality ({strength}%)
                  </p>
                  <p className="text-sm text-gray-700">
                    {strength >= 75
                      ? 'All four FCA elements are well-supported. Case suitable for qui tam filing consideration.'
                      : 'Some FCA elements need strengthening. Review the Evidence Gaps section for recommendations.'}
                  </p>
                </div>
              </div>
            </section>
          </div>
        </div>

        <div className="space-y-4">
          <button
            onClick={handleDownload}
            className="w-full bg-black text-white py-4 px-6 rounded-lg font-semibold hover:bg-gray-800 transition-colors flex items-center justify-center gap-2"
          >
            <Download className="w-5 h-5" />
            Download case memo
          </button>

          <button
            onClick={handleShare}
            className="w-full bg-white border-2 border-gray-300 text-gray-900 py-4 px-6 rounded-lg font-semibold hover:border-gray-400 transition-colors flex items-center justify-center gap-2"
          >
            <Share2 className="w-5 h-5" />
            Copy link
          </button>
        </div>

        <p className="text-center text-sm text-gray-500 mt-6">
          Generated using QuiTam Copilot AI · Not a substitute for legal advice
        </p>
      </main>
    </div>
  );
}
